
package com.shop.controller;

import com.shop.util.DBConnection;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Bashir Hossain
 */
public class Stationery extends javax.swing.JFrame {

    Connection con;
    Statement prst;
    
    /**
     * Creates new form Stocks
     */
    public Stationery() {
        initComponents();
        
        getContentPane().setBackground(new java.awt.Color(0, 102, 102));
        
        //DisplayTable();
        table_update();
    }

    
      public void resetStocksField() {
        barcode.setText("");
        productName.setText("");
        branch.setText("");
        qt.setText("");
        unitPrice.setText("");
        disscount.setText("");
        categories.setText("");
        phone.setText("");
        inputerName.setText("");
        date.setText("");
        searchByProductField1.setText("");
        
    }
    
    
     //id.setText((String) dr.getValueAt(sindex, 1));
//    barcode.setText((String) dr.getValueAt(sindex, 1));
//    productName.setText((String) dr.getValueAt(sindex, 2));
//    branch.setText((String) dr.getValueAt(sindex, 3));
//    qt.setText((String) dr.getValueAt(sindex, 4));
//    unitPrice.setText((String) dr.getValueAt(sindex, 5));
//    disscount.setText((String) dr.getValueAt(sindex, 6));
//    categories.setText((String) dr.getValueAt(sindex, 7));
//    inputerName.setText((String) dr.getValueAt(sindex, 8));
//    phone.setText((String) dr.getValueAt(sindex, 9));
//    date.setText((String) dr.getValueAt(sindex, 10));

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        stocksTable1 = new javax.swing.JTable();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        searchByProductField1 = new javax.swing.JTextField();
        homeButton1 = new javax.swing.JButton();
        printButton2 = new javax.swing.JButton();
        exitButton3 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        searchByCode = new javax.swing.JButton();
        deleteStockData = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        unitPrice = new javax.swing.JTextField();
        disscount = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        qt = new javax.swing.JTextField();
        inputerName = new javax.swing.JTextField();
        barcode = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        categories = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        updateStockTable = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stationery Stocks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        stocksTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "barcode", "product_name", "branch", "quantity", "unit_price", "discount", "catagories", "inputer_name", "phone", "date"
            }
        ));
        stocksTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stocksTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stocksTable1);

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane2.setBackground(new java.awt.Color(0, 102, 102));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLayeredPane2.setOpaque(true);

        searchByProductField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        searchByProductField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchByProductField1KeyReleased(evt);
            }
        });

        homeButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        homeButton1.setText("Home");
        homeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton1ActionPerformed(evt);
            }
        });

        printButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        printButton2.setText("Print");
        printButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButton2ActionPerformed(evt);
            }
        });

        exitButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exitButton3.setText("Exit");
        exitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton3ActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        searchByCode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchByCode.setText("Search By Code");
        searchByCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCodeActionPerformed(evt);
            }
        });

        deleteStockData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        deleteStockData.setText("Delete");
        deleteStockData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStockDataActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        unitPrice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        disscount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        disscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disscountActionPerformed(evt);
            }
        });

        phone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        qt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        inputerName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        barcode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        productName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        branch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        categories.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Barcode");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Name");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Branch");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Unit Price");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Disscount");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categories");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Inputer Name");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date");

        updateStockTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        updateStockTable.setText("Update");
        updateStockTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStockTableActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("All Products");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(searchByProductField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(homeButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(printButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(exitButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(reset, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(searchByCode, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(deleteStockData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(date, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(unitPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(disscount, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(phone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(qt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(inputerName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(barcode, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(productName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(branch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(categories, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(updateStockTable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barcode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productName)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(printButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31)))))
                .addGap(2, 2, 2)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteStockData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateStockTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByProductField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(branch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unitPrice))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                .addGap(21, 21, 21)))
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addGap(29, 29, 29))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(disscount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categories)
                                .addGap(6, 6, 6)))
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(inputerName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addGap(58, 58, 58)))))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputerName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(unitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(disscount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(categories, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(homeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(printButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchByProductField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchByCode, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exitButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updateStockTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteStockData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane2))
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
        //============= DATABASE TABLE SHOWING IN ADD PRODUCT FORM ========================//
//    private void DisplayTable(){
//    
//    try{
//    con = DBConnection.getConnection();
//    prst = con.createStatement();
//    String sql = "select * from product_entry";
//    
//    PreparedStatement prst = con.prepareStatement(sql);
//    ResultSet rs = prst.executeQuery();
//    stocksTable1.setModel(DbUtils.resultSetToTableModel(rs));
//   
//    }catch(Exception e)
//    {
//    JOptionPane.showMessageDialog(null, e);
//    }
//    }
    
    
        private void table_update() {
        int c;
        try {
            con = DBConnection.getConnection();
             prst = con.createStatement();
            String sql = "select * from product_entry where catagories = 'Grocery' "; // 
            
            PreparedStatement prst = con.prepareStatement(sql);
            ResultSet rs = prst.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            DefaultTableModel dr = (DefaultTableModel) stocksTable1.getModel();
            dr.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int a = 1; a <= c; a++) {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("barcode"));
                    v2.add(rs.getString("product_name"));
                    v2.add(rs.getString("branch"));
                    v2.add(rs.getString("quantity"));
                    v2.add(rs.getString("unit_price"));
                    v2.add(rs.getString("discount"));
                    v2.add(rs.getString("catagories"));
                    v2.add(rs.getString("inputer_name"));
                    v2.add(rs.getString("phone"));
                    v2.add(rs.getString("date"));
                    
                }
                dr.addRow(v2);
            }

        } catch (SQLException ex) {
           // Logger.getLogger(StudentRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
 
        
    private void homeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton1ActionPerformed
        this.setVisible(false);
        new Dashboard().setVisible(true);
        
        
    }//GEN-LAST:event_homeButton1ActionPerformed

    private void exitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton3ActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_exitButton3ActionPerformed

    private void printButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButton2ActionPerformed
          try {
            boolean print = stocksTable1.print();
            if (!print) {
                JOptionPane.showMessageDialog(null, "Unable To Print !!..");
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_printButton2ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
     //DisplayTable();
     resetStocksField();
    }//GEN-LAST:event_resetActionPerformed

    private void disscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disscountActionPerformed

    
    
    //============= Show data by clicking database table (By mouse click event) ==================//
    private void stocksTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocksTable1MouseClicked

    DefaultTableModel dr = (DefaultTableModel) stocksTable1.getModel();
    int sindex = stocksTable1.getSelectedRow();

    //id.setText((String) dr.getValueAt(sindex, 1));
    barcode.setText((String) dr.getValueAt(sindex, 1));
    productName.setText((String) dr.getValueAt(sindex, 2));
    branch.setText((String) dr.getValueAt(sindex, 3));
    qt.setText((String) dr.getValueAt(sindex, 4));
    unitPrice.setText((String) dr.getValueAt(sindex, 5));
    disscount.setText((String) dr.getValueAt(sindex, 6));
    categories.setText((String) dr.getValueAt(sindex, 7));
    inputerName.setText((String) dr.getValueAt(sindex, 8));
    phone.setText((String) dr.getValueAt(sindex, 9));
    date.setText((String) dr.getValueAt(sindex, 10));

    }//GEN-LAST:event_stocksTable1MouseClicked

    private void searchByCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCodeActionPerformed
         try {
            con = DBConnection.getConnection();
            prst = con.createStatement();
            String sql = "select * from product_entry where barcode = ?";

            PreparedStatement prst = con.prepareStatement(sql);
            prst.setString(1, searchByProductField1.getText());

            ResultSet rs = prst.executeQuery();
            if (rs.next()) {

                barcode.setText(rs.getString("barcode"));
                productName.setText(rs.getString("product_name"));
                branch.setText(rs.getString("branch"));
                qt.setText(String.valueOf(rs.getInt("quantity")));
                unitPrice.setText(String.valueOf(rs.getDouble("unit_price")));
                disscount.setText(String.valueOf(rs.getDouble("discount")));
                categories.setText(rs.getString("catagories"));
                inputerName.setText(rs.getString("inputer_name"));
                phone.setText(rs.getString("phone"));
                date.setText(rs.getString("date")); 
                
            } else {
                JOptionPane.showMessageDialog(null, "Record Not found");
            }
            con.close(); //after completing task close the popup window
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchByCodeActionPerformed

    private void searchByProductField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchByProductField1KeyReleased
               
               String search = searchByProductField1.getText().trim();  //For auto search

        if (search.equals("")) {
            resetStocksField();
        } else { 
        
        try {
            con = DBConnection.getConnection();
            prst = con.createStatement();
            String sql = "select * from product_entry where barcode = ?";

            PreparedStatement prst = con.prepareStatement(sql);
            prst.setString(1, searchByProductField1.getText());

            ResultSet rs = prst.executeQuery();
            if (rs.next()) {

                barcode.setText(rs.getString("barcode"));
                productName.setText(rs.getString("product_name"));
                branch.setText(rs.getString("branch"));
                qt.setText(String.valueOf(rs.getInt("quantity")));
                unitPrice.setText(String.valueOf(rs.getDouble("unit_price")));
                disscount.setText(String.valueOf(rs.getDouble("discount")));
                categories.setText(rs.getString("catagories"));
                inputerName.setText(rs.getString("inputer_name"));
                phone.setText(rs.getString("phone"));
                date.setText(rs.getString("date")); 
                
            } else {
                //JOptionPane.showMessageDialog(null, "Record Not found");
            }
            con.close(); //after completing task close the popup window
        } catch (Exception e) {
           // JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_searchByProductField1KeyReleased

    private void deleteStockDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStockDataActionPerformed
         try {
            con = DBConnection.getConnection();
            prst = con.createStatement();
            String sql = "delete from product_entry where barcode = ?";

            PreparedStatement prst = con.prepareStatement(sql);
            prst.setString(1, barcode.getText());

            
            
            prst.executeUpdate();
            JOptionPane.showConfirmDialog(null, "Do you want to delete");
            //JOptionPane.showMessageDialog(null, "Deleted Successfully");

           resetStocksField();
            table_update();//Refresh Table

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Deletion");
        }
    }//GEN-LAST:event_deleteStockDataActionPerformed

    private void updateStockTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStockTableActionPerformed
        try {
            con = DBConnection.getConnection();
            prst = con.createStatement();
            String sql = "update product_entry set product_name = ?, branch = ?, quantity = ?, unit_price = ?, discount = ?, catagories = ?, inputer_name = ?, phone = ?, date = ? where barcode = ?";

            PreparedStatement prst = con.prepareStatement(sql);
            
            prst.setString(1, productName.getText());
           // prst.setInt(2, Integer.parseInt(branch.getText()));
            prst.setString(2, branch.getText());
            prst.setInt(3, Integer.parseInt(qt.getText()));
            prst.setDouble(4, Double.parseDouble(unitPrice.getText()));
            prst.setDouble(5, Double.parseDouble(disscount.getText()));
            prst.setString(6, categories.getText());
            prst.setString(7, inputerName.getText());
            prst.setString(8, phone.getText());
            prst.setString(9, date.getText());

            prst.setString(10, barcode.getText());
            
            

            prst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Updated successfully");

          
            table_update();//Refresh Table

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateStockTableActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.setVisible(false);
        new Stocks().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stationery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stationery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stationery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stationery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stationery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcode;
    private javax.swing.JTextField branch;
    private javax.swing.JTextField categories;
    private javax.swing.JTextField date;
    private javax.swing.JButton deleteStockData;
    private javax.swing.JTextField disscount;
    private javax.swing.JButton exitButton3;
    private javax.swing.JButton homeButton1;
    private javax.swing.JTextField inputerName;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phone;
    private javax.swing.JButton printButton2;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField qt;
    private javax.swing.JButton reset;
    private javax.swing.JButton searchByCode;
    private javax.swing.JTextField searchByProductField1;
    private javax.swing.JTable stocksTable1;
    private javax.swing.JTextField unitPrice;
    private javax.swing.JButton updateStockTable;
    // End of variables declaration//GEN-END:variables
}
